### PR TITLE
shc_alpha, shc_beta, shc_gamma added

### PR DESCRIPTION
**Pull request by manxkim**
The new parameters, also used in Wannier90, are added to the set of additional parameters.
There is also going to be a PR in -org.

### CODE REVIEW

**Comment by jaemolihm** [comment]
It seems that one *cannot* use the previous scheme of computing all 27 elements at once. Is this intended?

**Comment by manxkim** [comment]
Thank you for letting me know this. Not intended and I am going to add it.

**Comment by stepan-tsirkin** [comment]
Hi Minsu, it looks like the fermiOcean features disappear in the __integrate.py file with this PR.  Probably you missed it while resolving conflicts.could you correct it.

**Comment by manxkim** [comment]
During merging I unintendedly deleted that. I return this.

**Pull request merged**
